/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vendingmachine;
import java.util.Scanner;

import vendingmachine.GraphicalUserInterface.ChooseItem;
import vendingmachine.GraphicalUserInterface.GameWindow;
import vendingmachine.Log.LogIn;
import vendingmachine.Log.SignUp;
import vendingmachine.Log.User;
import vendingmachine.Role.Cashier;
import vendingmachine.Role.Cashier1;
import vendingmachine.Role.Seller;
import vendingmachine.tools.Counter;

public class App {

    public static void main(String[] args) {
        GameWindow window = new GameWindow();
        window.main(new String[2]);
    }

}
